### ISSUE TITLE
logout method not working 

### ISSUE THREAD

**Issue by yesidlazaro** [nikolajakshic/instagramauth#10]
hi, thanks in advance for your library, i having problems with the logout method , i call but but ai reopen the app and ask AuthManager.getInstance().isLoggedIn() always is returning true after call AuthManager.getInstance().logout()

**Comment by nikolajakshic** [comment]
I can not reproduce the bug. Please create a sample project which can be used to reproduce it.

**Comment by yesidlazaro** [comment]
> I can not reproduce the bug. Please create a sample project which can be used to reproduce it.

was my fault, the logout method is working fine , closing ..
