### ISSUE TITLE
API info requests

### ISSUE THREAD

**Issue by PinhaEsquilo** [nikolajakshic/instagramauth#4]
Sorry for various issues post!. how can i 'extract' more infos about profile?

```
{
  "data": {
    "id": "1574083",
    "username": "snoopdogg",
    "full_name": "Snoop Dogg",
    "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_1574083_75sq_1295469061.jpg",
    "bio": "This is my bio",
    "website": "http://snoopdogg.com",
    "is_business": false,
    "counts": {
      "media": 1320,
      "follows": 420,
      "followed_by": 3410
    }
  }
}
```

How can a use this? i tired to put this on strings = `<string name="follows">%1$s</string>`
Or i need to create new java to get those informations?

**Comment by nikolajakshic** [comment]
[UserInfo](https://github.com/nikolajakshic/instagramauth/blob/master/instagramauth/src/main/java/com/nikola/jakshic/instagramauth/UserInfo.kt) object holds all the data from that response:

```java
AuthManager.getInstance().getUserInfoAsync(new AuthManager.Callback<UserInfo>() {
    @Override
    public void onSuccess(UserInfo userInfo) {
        String id = userInfo.getId();
        String userName = userInfo.getUserName();
        String fullName = userInfo.getFullName();
        String photoUrl = userInfo.getPhotoUrl();
        String bio = userInfo.getBio();
        String website = userInfo.getWebsite();
        boolean isBusiness = userInfo.isBusiness();
        int media = userInfo.getCounts().getMedia();
        int follows = userInfo.getCounts().getFollows();
        int followedBy = userInfo.getCounts().getFollowedBy();

        nameTextView.setText("Name: " + userName);
        followingTextView.setText("Following: " + follows);
        followersTextView.setText("Followers: " + followedBy);
    }

    @Override
    public void onError(InstagramAuthException e) {
        // Handle error
    }
});
```

**Comment by PinhaEsquilo** [comment]
@nikolajakshic Another noob question! how can i get media things? `
int media = userInfo.getCounts.getMedia();
        int follows = userInfo.getCounts.getFollows();
        int followedBy = userInfo.getCounts.getFollowedBy();`
Why getCounts says 'Cannot resolve symbol 'getCounts'
![noob](https://user-images.githubusercontent.com/25893893/46263869-830fa780-c4eb-11e8-833b-8acb49f602c0.png)

**Comment by PinhaEsquilo** [comment]
Another noob question sorry :'( but how can i get the image?


![iamge](https://user-images.githubusercontent.com/25893893/46264134-4645af80-c4ef-11e8-95be-15b0d96936d1.png)

**Comment by PinhaEsquilo** [comment]
@nikolajakshic Thanks <3 no homo.
