### ISSUE TITLE
Photo bad quality when using 'wrap_content' for width.

### ISSUE THREAD

**Issue by PinhaEsquilo** [nikolajakshic/instagramauth#6]
Hi, again!. so... when i use the scaleType 'centerCrop' in 'wrap_content' for width my image got bad quality!. the image is on 1920x1080 how can i resolve this?.
![issue](https://user-images.githubusercontent.com/25893893/46933861-1f799400-d02c-11e8-82b8-cb3ddcbe76b2.png)

**Comment by nikolajakshic** [comment]
This has nothing to do with the library.

Instagram compresses image in order to reduce load times across the app and website, hence there is quality loss. Try experimenting with different sizes, format, etc.

**Comment by PinhaEsquilo** [comment]
@nikolajakshic Oh my bad, man! that's sad for my app... i going see what i can do for now. thanks again bro!.
