### ISSUE TITLE
Private profile can redirect for instagram app

### ISSUE THREAD

**Issue by PinhaEsquilo** [nikolajakshic/instagramauth#8]
When a user login with a private profile the api redirect for a instagram app LOL.

**Comment by nikolajakshic** [comment]
There was an issue where after clicking on the Instagram's "Log in" button, the screen would stuck on infinite loading bar or in some rare cases (your experience) it would redirect to another links. 
It is fixed in the new version.

It was nothing specific with the private profiles, it just happened that you experienced it that way.

**Comment by PinhaEsquilo** [comment]
> 
> 
> There was an issue where after clicking on the Instagram's "Log in" button, the screen would stuck on infinite loading bar or in some rare cases (your experience) it would redirect to another links.
> It is fixed in the new version.
> 
> It was nothing specific with the private profiles, it just happened that you experienced it that way.

Yeah, i almost open a new issue talking about 'stuck on infinite loading bar' because this happens alot now, but if you is working on for fixing that i don't need to open another issues anomore. and yeah this thing when users loggin with private profiles they are redirect to instagram app! but i will check if this bug still happens only with me. thanks for reply! happy new years brother!.

**Comment by nikolajakshic** [comment]
The new version (1.1.1) is live. Remember, you need to [migrate to AndroidX](https://developer.android.com/jetpack/androidx/migrate) if you are not already using it.

**Comment by PinhaEsquilo** [comment]
@nikolajakshic I migrate to AndroidX and I updated for (1.1.1) now everything is fine =D. awesome. thanks for your support again.
