### ISSUE TITLE
Login with facebook causes redirect to instagram app.

### ISSUE THREAD

**Issue by PinhaEsquilo** [nikolajakshic/instagramauth#9]
Hi again @nikolajakshic !. So... I don't know why but when i login with facebook instead instagram account causes redirect to instagram app!. my redirect on AndroidManifest is = "http://localhost" maybe this is the problem? because still i don't have a redirect link.

**Comment by nikolajakshic** [comment]
Does it happen every time you try to log in with facebook or is it random?
The only time I encountered weird behavior, was when I tried to log in with facebook but the accounts were not linked. After linking accounts I had no problems.

And about your redirect link, you don't need to buy domain or something like that, your redirect link can be anything, e.g. https://pinhaesquilo.com.

**Comment by PinhaEsquilo** [comment]
I sent you an email.
